version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: todolist-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - todonet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - todonet

volumes:
  dbdata:

networks:
  todonet:
    driver: bridge 